### ISSUE TITLE
Remove/depublish package on packagist

### ISSUE THREAD

**Issue by lstrojny** [ZendExperts/phpids#2]
PHPIDS is officially on GitHub and comes with composer support. See https://github.com/PHPIDS/PHPIDS

Could you depublish phpids on packagist?

**Comment by cosmin-harangus** [comment]
The PHPIDS mirror on packagist available at ZendExperts/phpids will still have to be kept at least until the numbers of installs reaches 0 for two consecutive months in order to maintain compatibility for previous versions of ZeSecurity.

Instead I will update the zendexperts/ze-security package to use the official PHPIDS package.

**Comment by lstrojny** [comment]
Issue is, that the official PHPIDS can’t be published as long as it exists on packagist. Could you reconsider?

**Comment by cosmin-harangus** [comment]
Not sure I understand... as far as I can see it is already on packagist, available here: https://packagist.org/packages/phpids/phpids 

The only one I have is this one:
https://packagist.org/packages/ZendExperts/phpids

But that should have no conflict with the official version. Please let me know if this is not the case.

**Comment by lstrojny** [comment]
Oh, wow, that’s interesting. It seemed not to work for me for the first time. So, everything is fine. Thanks and sorry for the confusion!

**Comment by cosmin-harangus** [comment]
No problem... glad I could help.
